/* 
 * Vimeo API
 *
 * Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.
 *
 * The version of the OpenAPI document: 3.4
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using VimeoOpenApi.Client;
using VimeoOpenApi.Api;
using VimeoOpenApi.Model;

namespace VimeoOpenApi.Test
{
    /// <summary>
    ///  Class for testing VideosContentRatingsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class VideosContentRatingsApiTests : IDisposable
    {
        private VideosContentRatingsApi instance;

        public VideosContentRatingsApiTests()
        {
            instance = new VideosContentRatingsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VideosContentRatingsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' VideosContentRatingsApi
            //Assert.IsType(typeof(VideosContentRatingsApi), instance, "instance is a VideosContentRatingsApi");
        }

        
        /// <summary>
        /// Test GetContentRatings
        /// </summary>
        [Fact]
        public void GetContentRatingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetContentRatings();
            //Assert.IsType<List<ContentRating>> (response, "response is List<ContentRating>");
        }
        
    }

}
