/* 
 * Vimeo API
 *
 * Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.
 *
 * The version of the OpenAPI document: 3.4
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using VimeoOpenApi.Client;
using VimeoOpenApi.Api;
using VimeoOpenApi.Model;

namespace VimeoOpenApi.Test
{
    /// <summary>
    ///  Class for testing VideosLiveM3U8PlaybackApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class VideosLiveM3U8PlaybackApiTests : IDisposable
    {
        private VideosLiveM3U8PlaybackApi instance;

        public VideosLiveM3U8PlaybackApiTests()
        {
            instance = new VideosLiveM3U8PlaybackApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VideosLiveM3U8PlaybackApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' VideosLiveM3U8PlaybackApi
            //Assert.IsType(typeof(VideosLiveM3U8PlaybackApi), instance, "instance is a VideosLiveM3U8PlaybackApi");
        }

        
        /// <summary>
        /// Test GetOneTimeEventM3u8Playback
        /// </summary>
        [Fact]
        public void GetOneTimeEventM3u8PlaybackTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //decimal userId = null;
            //decimal videoId = null;
            //instance.GetOneTimeEventM3u8Playback(userId, videoId);
            
        }
        
        /// <summary>
        /// Test GetOneTimeEventM3u8PlaybackAlt1
        /// </summary>
        [Fact]
        public void GetOneTimeEventM3u8PlaybackAlt1Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //decimal videoId = null;
            //instance.GetOneTimeEventM3u8PlaybackAlt1(videoId);
            
        }
        
    }

}
