/* 
 * Vimeo API
 *
 * Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.
 *
 * The version of the OpenAPI document: 3.4
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using VimeoOpenApi.Api;
using VimeoOpenApi.Model;
using VimeoOpenApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace VimeoOpenApi.Test
{
    /// <summary>
    ///  Class for testing Activity31Metadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class Activity31MetadataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Activity31Metadata
        //private Activity31Metadata instance;

        public Activity31MetadataTests()
        {
            // TODO uncomment below to create an instance of Activity31Metadata
            //instance = new Activity31Metadata();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Activity31Metadata
        /// </summary>
        [Fact]
        public void Activity31MetadataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Activity31Metadata
            //Assert.IsInstanceOfType<Activity31Metadata> (instance, "variable 'instance' is a Activity31Metadata");
        }


        /// <summary>
        /// Test the property 'Connections'
        /// </summary>
        [Fact]
        public void ConnectionsTest()
        {
            // TODO unit test for the property 'Connections'
        }

    }

}
