/* 
 * Vimeo API
 *
 * Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.
 *
 * The version of the OpenAPI document: 3.4
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using VimeoOpenApi.Api;
using VimeoOpenApi.Model;
using VimeoOpenApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace VimeoOpenApi.Test
{
    /// <summary>
    ///  Class for testing AlbumPrivacy
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AlbumPrivacyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AlbumPrivacy
        //private AlbumPrivacy instance;

        public AlbumPrivacyTests()
        {
            // TODO uncomment below to create an instance of AlbumPrivacy
            //instance = new AlbumPrivacy();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AlbumPrivacy
        /// </summary>
        [Fact]
        public void AlbumPrivacyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AlbumPrivacy
            //Assert.IsInstanceOfType<AlbumPrivacy> (instance, "variable 'instance' is a AlbumPrivacy");
        }


        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'View'
        /// </summary>
        [Fact]
        public void ViewTest()
        {
            // TODO unit test for the property 'View'
        }

    }

}
