/* 
 * Vimeo API
 *
 * Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.
 *
 * The version of the OpenAPI document: 3.4
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using VimeoOpenApi.Api;
using VimeoOpenApi.Model;
using VimeoOpenApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace VimeoOpenApi.Test
{
    /// <summary>
    ///  Class for testing InlineObject57
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineObject57Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineObject57
        //private InlineObject57 instance;

        public InlineObject57Tests()
        {
            // TODO uncomment below to create an instance of InlineObject57
            //instance = new InlineObject57();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineObject57
        /// </summary>
        [Fact]
        public void InlineObject57InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineObject57
            //Assert.IsInstanceOfType<InlineObject57> (instance, "variable 'instance' is a InlineObject57");
        }


        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Role'
        /// </summary>
        [Fact]
        public void RoleTest()
        {
            // TODO unit test for the property 'Role'
        }
        /// <summary>
        /// Test the property 'UserUri'
        /// </summary>
        [Fact]
        public void UserUriTest()
        {
            // TODO unit test for the property 'UserUri'
        }

    }

}
