/* 
 * Vimeo API
 *
 * Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.
 *
 * The version of the OpenAPI document: 3.4
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using VimeoOpenApi.Api;
using VimeoOpenApi.Model;
using VimeoOpenApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace VimeoOpenApi.Test
{
    /// <summary>
    ///  Class for testing InlineObject36
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineObject36Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineObject36
        //private InlineObject36 instance;

        public InlineObject36Tests()
        {
            // TODO uncomment below to create an instance of InlineObject36
            //instance = new InlineObject36();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineObject36
        /// </summary>
        [Fact]
        public void InlineObject36InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineObject36
            //Assert.IsInstanceOfType<InlineObject36> (instance, "variable 'instance' is a InlineObject36");
        }


        /// <summary>
        /// Test the property 'Buy'
        /// </summary>
        [Fact]
        public void BuyTest()
        {
            // TODO unit test for the property 'Buy'
        }
        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Fact]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }
        /// <summary>
        /// Test the property 'ReleaseYear'
        /// </summary>
        [Fact]
        public void ReleaseYearTest()
        {
            // TODO unit test for the property 'ReleaseYear'
        }
        /// <summary>
        /// Test the property 'Rent'
        /// </summary>
        [Fact]
        public void RentTest()
        {
            // TODO unit test for the property 'Rent'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
