/* 
 * Vimeo API
 *
 * Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.
 *
 * The version of the OpenAPI document: 3.4
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using VimeoOpenApi.Api;
using VimeoOpenApi.Model;
using VimeoOpenApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace VimeoOpenApi.Test
{
    /// <summary>
    ///  Class for testing InlineObject42
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineObject42Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineObject42
        //private InlineObject42 instance;

        public InlineObject42Tests()
        {
            // TODO uncomment below to create an instance of InlineObject42
            //instance = new InlineObject42();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineObject42
        /// </summary>
        [Fact]
        public void InlineObject42InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineObject42
            //Assert.IsInstanceOfType<InlineObject42> (instance, "variable 'instance' is a InlineObject42");
        }


        /// <summary>
        /// Test the property 'Videos'
        /// </summary>
        [Fact]
        public void VideosTest()
        {
            // TODO unit test for the property 'Videos'
        }

    }

}
