/* 
 * Vimeo API
 *
 * Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.
 *
 * The version of the OpenAPI document: 3.4
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using VimeoOpenApi.Api;
using VimeoOpenApi.Model;
using VimeoOpenApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace VimeoOpenApi.Test
{
    /// <summary>
    ///  Class for testing InlineObject32
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineObject32Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineObject32
        //private InlineObject32 instance;

        public InlineObject32Tests()
        {
            // TODO uncomment below to create an instance of InlineObject32
            //instance = new InlineObject32();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineObject32
        /// </summary>
        [Fact]
        public void InlineObject32InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineObject32
            //Assert.IsInstanceOfType<InlineObject32> (instance, "variable 'instance' is a InlineObject32");
        }


        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }

    }

}
