/* 
 * Vimeo API
 *
 * Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.
 *
 * The version of the OpenAPI document: 3.4
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using VimeoOpenApi.Api;
using VimeoOpenApi.Model;
using VimeoOpenApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace VimeoOpenApi.Test
{
    /// <summary>
    ///  Class for testing MeOndemandPagesRent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MeOndemandPagesRentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MeOndemandPagesRent
        //private MeOndemandPagesRent instance;

        public MeOndemandPagesRentTests()
        {
            // TODO uncomment below to create an instance of MeOndemandPagesRent
            //instance = new MeOndemandPagesRent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MeOndemandPagesRent
        /// </summary>
        [Fact]
        public void MeOndemandPagesRentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MeOndemandPagesRent
            //Assert.IsInstanceOfType<MeOndemandPagesRent> (instance, "variable 'instance' is a MeOndemandPagesRent");
        }


        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
        /// <summary>
        /// Test the property 'Period'
        /// </summary>
        [Fact]
        public void PeriodTest()
        {
            // TODO unit test for the property 'Period'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }

    }

}
