/* 
 * Vimeo API
 *
 * Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.
 *
 * The version of the OpenAPI document: 3.4
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using VimeoOpenApi.Api;
using VimeoOpenApi.Model;
using VimeoOpenApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace VimeoOpenApi.Test
{
    /// <summary>
    ///  Class for testing MeVideos
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MeVideosTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MeVideos
        //private MeVideos instance;

        public MeVideosTests()
        {
            // TODO uncomment below to create an instance of MeVideos
            //instance = new MeVideos();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MeVideos
        /// </summary>
        [Fact]
        public void MeVideosInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MeVideos
            //Assert.IsInstanceOfType<MeVideos> (instance, "variable 'instance' is a MeVideos");
        }


        /// <summary>
        /// Test the property 'Privacy'
        /// </summary>
        [Fact]
        public void PrivacyTest()
        {
            // TODO unit test for the property 'Privacy'
        }

    }

}
