/* 
 * Vimeo API
 *
 * Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.
 *
 * The version of the OpenAPI document: 3.4
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using VimeoOpenApi.Api;
using VimeoOpenApi.Model;
using VimeoOpenApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace VimeoOpenApi.Test
{
    /// <summary>
    ///  Class for testing MeVideosEmbedTitle
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MeVideosEmbedTitleTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MeVideosEmbedTitle
        //private MeVideosEmbedTitle instance;

        public MeVideosEmbedTitleTests()
        {
            // TODO uncomment below to create an instance of MeVideosEmbedTitle
            //instance = new MeVideosEmbedTitle();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MeVideosEmbedTitle
        /// </summary>
        [Fact]
        public void MeVideosEmbedTitleInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MeVideosEmbedTitle
            //Assert.IsInstanceOfType<MeVideosEmbedTitle> (instance, "variable 'instance' is a MeVideosEmbedTitle");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Owner'
        /// </summary>
        [Fact]
        public void OwnerTest()
        {
            // TODO unit test for the property 'Owner'
        }
        /// <summary>
        /// Test the property 'Portrait'
        /// </summary>
        [Fact]
        public void PortraitTest()
        {
            // TODO unit test for the property 'Portrait'
        }

    }

}
