/* 
 * Vimeo API
 *
 * Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.
 *
 * The version of the OpenAPI document: 3.4
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using VimeoOpenApi.Api;
using VimeoOpenApi.Model;
using VimeoOpenApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace VimeoOpenApi.Test
{
    /// <summary>
    ///  Class for testing OnDemandVideoRent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OnDemandVideoRentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OnDemandVideoRent
        //private OnDemandVideoRent instance;

        public OnDemandVideoRentTests()
        {
            // TODO uncomment below to create an instance of OnDemandVideoRent
            //instance = new OnDemandVideoRent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OnDemandVideoRent
        /// </summary>
        [Fact]
        public void OnDemandVideoRentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OnDemandVideoRent
            //Assert.IsInstanceOfType<OnDemandVideoRent> (instance, "variable 'instance' is a OnDemandVideoRent");
        }


        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'Purchased'
        /// </summary>
        [Fact]
        public void PurchasedTest()
        {
            // TODO unit test for the property 'Purchased'
        }

    }

}
