/* 
 * Vimeo API
 *
 * Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.
 *
 * The version of the OpenAPI document: 3.4
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using VimeoOpenApi.Api;
using VimeoOpenApi.Model;
using VimeoOpenApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace VimeoOpenApi.Test
{
    /// <summary>
    ///  Class for testing OnDemandPagePreorder
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OnDemandPagePreorderTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OnDemandPagePreorder
        //private OnDemandPagePreorder instance;

        public OnDemandPagePreorderTests()
        {
            // TODO uncomment below to create an instance of OnDemandPagePreorder
            //instance = new OnDemandPagePreorder();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OnDemandPagePreorder
        /// </summary>
        [Fact]
        public void OnDemandPagePreorderInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OnDemandPagePreorder
            //Assert.IsInstanceOfType<OnDemandPagePreorder> (instance, "variable 'instance' is a OnDemandPagePreorder");
        }


        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
        /// <summary>
        /// Test the property 'CancelTime'
        /// </summary>
        [Fact]
        public void CancelTimeTest()
        {
            // TODO unit test for the property 'CancelTime'
        }
        /// <summary>
        /// Test the property 'PublishTime'
        /// </summary>
        [Fact]
        public void PublishTimeTest()
        {
            // TODO unit test for the property 'PublishTime'
        }
        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Fact]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }

    }

}
