/* 
 * Vimeo API
 *
 * Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.
 *
 * The version of the OpenAPI document: 3.4
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using VimeoOpenApi.Api;
using VimeoOpenApi.Model;
using VimeoOpenApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace VimeoOpenApi.Test
{
    /// <summary>
    ///  Class for testing PictureSizes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PictureSizesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PictureSizes
        //private PictureSizes instance;

        public PictureSizesTests()
        {
            // TODO uncomment below to create an instance of PictureSizes
            //instance = new PictureSizes();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PictureSizes
        /// </summary>
        [Fact]
        public void PictureSizesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PictureSizes
            //Assert.IsInstanceOfType<PictureSizes> (instance, "variable 'instance' is a PictureSizes");
        }


        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Fact]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }
        /// <summary>
        /// Test the property 'Link'
        /// </summary>
        [Fact]
        public void LinkTest()
        {
            // TODO unit test for the property 'Link'
        }
        /// <summary>
        /// Test the property 'LinkWithPlayButton'
        /// </summary>
        [Fact]
        public void LinkWithPlayButtonTest()
        {
            // TODO unit test for the property 'LinkWithPlayButton'
        }
        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Fact]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }

    }

}
