/* 
 * Vimeo API
 *
 * Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.
 *
 * The version of the OpenAPI document: 3.4
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using VimeoOpenApi.Api;
using VimeoOpenApi.Model;
using VimeoOpenApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace VimeoOpenApi.Test
{
    /// <summary>
    ///  Class for testing PresetsSettingsLogos
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PresetsSettingsLogosTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PresetsSettingsLogos
        //private PresetsSettingsLogos instance;

        public PresetsSettingsLogosTests()
        {
            // TODO uncomment below to create an instance of PresetsSettingsLogos
            //instance = new PresetsSettingsLogos();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PresetsSettingsLogos
        /// </summary>
        [Fact]
        public void PresetsSettingsLogosInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PresetsSettingsLogos
            //Assert.IsInstanceOfType<PresetsSettingsLogos> (instance, "variable 'instance' is a PresetsSettingsLogos");
        }


        /// <summary>
        /// Test the property 'Custom'
        /// </summary>
        [Fact]
        public void CustomTest()
        {
            // TODO unit test for the property 'Custom'
        }
        /// <summary>
        /// Test the property 'StickyCustom'
        /// </summary>
        [Fact]
        public void StickyCustomTest()
        {
            // TODO unit test for the property 'StickyCustom'
        }
        /// <summary>
        /// Test the property 'Vimeo'
        /// </summary>
        [Fact]
        public void VimeoTest()
        {
            // TODO unit test for the property 'Vimeo'
        }

    }

}
