/* 
 * Vimeo API
 *
 * Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.
 *
 * The version of the OpenAPI document: 3.4
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using VimeoOpenApi.Api;
using VimeoOpenApi.Model;
using VimeoOpenApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace VimeoOpenApi.Test
{
    /// <summary>
    ///  Class for testing PresetsSettingsOutro
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PresetsSettingsOutroTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PresetsSettingsOutro
        //private PresetsSettingsOutro instance;

        public PresetsSettingsOutroTests()
        {
            // TODO uncomment below to create an instance of PresetsSettingsOutro
            //instance = new PresetsSettingsOutro();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PresetsSettingsOutro
        /// </summary>
        [Fact]
        public void PresetsSettingsOutroInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PresetsSettingsOutro
            //Assert.IsInstanceOfType<PresetsSettingsOutro> (instance, "variable 'instance' is a PresetsSettingsOutro");
        }


        /// <summary>
        /// Test the property 'Clips'
        /// </summary>
        [Fact]
        public void ClipsTest()
        {
            // TODO unit test for the property 'Clips'
        }
        /// <summary>
        /// Test the property 'Link'
        /// </summary>
        [Fact]
        public void LinkTest()
        {
            // TODO unit test for the property 'Link'
        }
        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Videos'
        /// </summary>
        [Fact]
        public void VideosTest()
        {
            // TODO unit test for the property 'Videos'
        }

    }

}
