/* 
 * Vimeo API
 *
 * Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.
 *
 * The version of the OpenAPI document: 3.4
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using VimeoOpenApi.Api;
using VimeoOpenApi.Model;
using VimeoOpenApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace VimeoOpenApi.Test
{
    /// <summary>
    ///  Class for testing UserMetadataConnectionsFolders
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserMetadataConnectionsFoldersTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserMetadataConnectionsFolders
        //private UserMetadataConnectionsFolders instance;

        public UserMetadataConnectionsFoldersTests()
        {
            // TODO uncomment below to create an instance of UserMetadataConnectionsFolders
            //instance = new UserMetadataConnectionsFolders();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserMetadataConnectionsFolders
        /// </summary>
        [Fact]
        public void UserMetadataConnectionsFoldersInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserMetadataConnectionsFolders
            //Assert.IsInstanceOfType<UserMetadataConnectionsFolders> (instance, "variable 'instance' is a UserMetadataConnectionsFolders");
        }


        /// <summary>
        /// Test the property 'Options'
        /// </summary>
        [Fact]
        public void OptionsTest()
        {
            // TODO unit test for the property 'Options'
        }
        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }
        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [Fact]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }

    }

}
