/* 
 * Vimeo API
 *
 * Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.
 *
 * The version of the OpenAPI document: 3.4
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using VimeoOpenApi.Api;
using VimeoOpenApi.Model;
using VimeoOpenApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace VimeoOpenApi.Test
{
    /// <summary>
    ///  Class for testing VideoVersions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VideoVersionsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VideoVersions
        //private VideoVersions instance;

        public VideoVersionsTests()
        {
            // TODO uncomment below to create an instance of VideoVersions
            //instance = new VideoVersions();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VideoVersions
        /// </summary>
        [Fact]
        public void VideoVersionsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" VideoVersions
            //Assert.IsInstanceOfType<VideoVersions> (instance, "variable 'instance' is a VideoVersions");
        }


        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
        /// <summary>
        /// Test the property 'App'
        /// </summary>
        [Fact]
        public void AppTest()
        {
            // TODO unit test for the property 'App'
        }
        /// <summary>
        /// Test the property 'CreatedTime'
        /// </summary>
        [Fact]
        public void CreatedTimeTest()
        {
            // TODO unit test for the property 'CreatedTime'
        }
        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Fact]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }
        /// <summary>
        /// Test the property 'Filename'
        /// </summary>
        [Fact]
        public void FilenameTest()
        {
            // TODO unit test for the property 'Filename'
        }
        /// <summary>
        /// Test the property 'Filesize'
        /// </summary>
        [Fact]
        public void FilesizeTest()
        {
            // TODO unit test for the property 'Filesize'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
        /// <summary>
        /// Test the property 'ModifiedTime'
        /// </summary>
        [Fact]
        public void ModifiedTimeTest()
        {
            // TODO unit test for the property 'ModifiedTime'
        }
        /// <summary>
        /// Test the property 'Upload'
        /// </summary>
        [Fact]
        public void UploadTest()
        {
            // TODO unit test for the property 'Upload'
        }
        /// <summary>
        /// Test the property 'UploadDate'
        /// </summary>
        [Fact]
        public void UploadDateTest()
        {
            // TODO unit test for the property 'UploadDate'
        }
        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [Fact]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }
        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }

    }

}
