/* 
 * Vimeo API
 *
 * Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.
 *
 * The version of the OpenAPI document: 3.4
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = VimeoOpenApi.Client.OpenAPIDateConverter;

namespace VimeoOpenApi.Model
{
    /// <summary>
    /// InlineObject28
    /// </summary>
    [DataContract]
    public partial class InlineObject28 :  IEquatable<InlineObject28>, IValidatableObject
    {
        /// <summary>
        /// The grant type. The value of this field must be &#x60;client_credentials&#x60;.
        /// </summary>
        /// <value>The grant type. The value of this field must be &#x60;client_credentials&#x60;.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum GrantTypeEnum
        {
            /// <summary>
            /// Enum Clientcredentials for value: client_credentials
            /// </summary>
            [EnumMember(Value = "client_credentials")]
            Clientcredentials = 1

        }

        /// <summary>
        /// The grant type. The value of this field must be &#x60;client_credentials&#x60;.
        /// </summary>
        /// <value>The grant type. The value of this field must be &#x60;client_credentials&#x60;.</value>
        [DataMember(Name="grant_type", EmitDefaultValue=false)]
        public GrantTypeEnum GrantType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineObject28" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InlineObject28() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineObject28" /> class.
        /// </summary>
        /// <param name="grantType">The grant type. The value of this field must be &#x60;client_credentials&#x60;. (required).</param>
        /// <param name="scope">A space-separated list of the authentication scopes to access. The default is &#x60;public&#x60;. (required).</param>
        public InlineObject28(GrantTypeEnum grantType = default(GrantTypeEnum), string scope = default(string))
        {
            this.GrantType = grantType;
            // to ensure "scope" is required (not null)
            this.Scope = scope ?? throw new ArgumentNullException("scope is a required property for InlineObject28 and cannot be null");
        }
        
        /// <summary>
        /// A space-separated list of the authentication scopes to access. The default is &#x60;public&#x60;.
        /// </summary>
        /// <value>A space-separated list of the authentication scopes to access. The default is &#x60;public&#x60;.</value>
        [DataMember(Name="scope", EmitDefaultValue=false)]
        public string Scope { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineObject28 {\n");
            sb.Append("  GrantType: ").Append(GrantType).Append("\n");
            sb.Append("  Scope: ").Append(Scope).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InlineObject28);
        }

        /// <summary>
        /// Returns true if InlineObject28 instances are equal
        /// </summary>
        /// <param name="input">Instance of InlineObject28 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineObject28 input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.GrantType == input.GrantType ||
                    this.GrantType.Equals(input.GrantType)
                ) && 
                (
                    this.Scope == input.Scope ||
                    (this.Scope != null &&
                    this.Scope.Equals(input.Scope))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.GrantType.GetHashCode();
                if (this.Scope != null)
                    hashCode = hashCode * 59 + this.Scope.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
