/* 
 * Vimeo API
 *
 * Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.
 *
 * The version of the OpenAPI document: 3.4
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = VimeoOpenApi.Client.OpenAPIDateConverter;

namespace VimeoOpenApi.Model
{
    /// <summary>
    /// MeOndemandPagesSubscription
    /// </summary>
    [DataContract]
    public partial class MeOndemandPagesSubscription :  IEquatable<MeOndemandPagesSubscription>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MeOndemandPagesSubscription" /> class.
        /// </summary>
        /// <param name="monthly">monthly.</param>
        public MeOndemandPagesSubscription(MeOndemandPagesSubscriptionMonthly monthly = default(MeOndemandPagesSubscriptionMonthly))
        {
            this.Monthly = monthly;
        }
        
        /// <summary>
        /// Gets or Sets Monthly
        /// </summary>
        [DataMember(Name="monthly", EmitDefaultValue=false)]
        public MeOndemandPagesSubscriptionMonthly Monthly { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MeOndemandPagesSubscription {\n");
            sb.Append("  Monthly: ").Append(Monthly).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MeOndemandPagesSubscription);
        }

        /// <summary>
        /// Returns true if MeOndemandPagesSubscription instances are equal
        /// </summary>
        /// <param name="input">Instance of MeOndemandPagesSubscription to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MeOndemandPagesSubscription input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Monthly == input.Monthly ||
                    (this.Monthly != null &&
                    this.Monthly.Equals(input.Monthly))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Monthly != null)
                    hashCode = hashCode * 59 + this.Monthly.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
